### ISSUE TITLE
Translate to PT-BR

### ISSUE THREAD

**Issue by OliveiraCleidson** [mrtolkien/inhouse_bot#25]
I want to translate the bot to 'pt-BR', I think we can create a JSON for each language that defaults to English, but I would need a service that would load the translation files in the other services.

How could we implement this? A factory that generates an instance of a class that through its methods takes the text in the configured JSON?

I don't know Python, just GO and Javascript (Typescript), I will learn Python to try to contribute to this incredible project and I thank you for the bot.

I will run the translation replacing the English text for now on another branch.

**Comment by mrtolkien** [comment]
Hello!

In Python there are a few ways to handle translation, and the most "standard" would be to use `gettext` which is part of the standard library.

Unfortunately it is quite a bit of work to set up the whole project properly to support localization, in particular since `discord.py` relies on docstrings for a lot of things. I am not sure I will do it myself as I am focusing on other projects at the moment!

**Comment by OliveiraCleidson** [comment]
I can configure the project to have a configuration module that feeds the text and perhaps other settings into the system without breaking the current system.

I understand how well architecture, work with microservices and api rest, I just don't know yet the python syntax can I work on this feature? Of course, with some instructions on another branch.

**Comment by OliveiraCleidson** [comment]
I still haven't read the code to understand the whole system, but in a few days I can contribute.
